---
- hosts: thuis ubuntu klanten
  become: true
  become_user: root
  tasks:
    - name: Bijwerken
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Updateb
      apt: upgrade=dist force_apt_get=yes

    - name: Opschonen
      apt:
        autoremove: yes
        
    - name: Nu dan
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot
      reboot:
        msg: "Reboot wokkawokka yolo"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
